name: Code Quality

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black isort mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run ruff
      run: ruff check .
    
    - name: Check black formatting
      run: black --check .
    
    - name: Check import sorting
      run: isort --check-only .
    
    - name: Run type checking
      run: mypy .